# Generated by Django 5.2.6 on 2025-09-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoRuleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_progreso', models.BooleanField(default=False)),
                ('numeros_vendidos', models.TextField(default='[]')),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('ganador', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='premios/')),
            ],
        ),
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('gmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('hoja', models.IntegerField(default=1, help_text='Número de hoja a la que pertenece este número')),
            ],
            options={
                'unique_together': {('valor', 'hoja')},
            },
        ),
    ]
