# Generated by Django for adding categoria to Premio
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='categoria',
            field=models.CharField(
                max_length=3,
                choices=[('1er', '1er Lugar'), ('2do', '2do Lugar'), ('3er', '3er Lugar')],
                default='1er',
            ),
        ),
    ]
