# Generated by Django 5.2.6 on 2025-09-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_premio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
