# Generated by Django 5.2.6 on 2025-09-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_publicidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='categoria',
            field=models.CharField(choices=[('1er', '1er Lugar'), ('2do', '2do Lugar'), ('3er', '3er Lugar'), ('sec', 'Secundario')], default='1er', max_length=3),
        ),
    ]
