# Generated by Django 5.2.6 on 2025-09-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_alter_premio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
