# Generated by Django 5.2.6 on 2025-09-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_alter_premio_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='numero',
            name='asistencia',
            field=models.BooleanField(default=False),
        ),
    ]
